Fix link to Belgium customs regarding HS code tariff
myparcelbe/woocommerce pull request #164
Opened 2021-05-27 12:08 UTC by joerivanveen

2021-05-27 12:42 UTC, RichardPerdaan approved these changes

2021-05-27 13:07 UTC, EdieLemoine requested changes

2021-05-27 13:07 UTC, EdieLemoine commented on languages/woocommerce-myparcelbe-fr_BE.po
> +msgid "product_option_hs_code_helpt_text_%stariff_website%s"
Ik denk niet dat dit een goed idee is, kun je die variabelen beperken tot de daadwerkelijke inhoud van de vertaling?

2021-06-01 07:57 UTC, RichardPerdaan approved these changes

2021-06-01 14:51 UTC, EdieLemoine approved these changes

2021-06-10 07:44 UTC, RichardPerdaan approved these changes

2021-06-11 07:51 UTC, merged