My 29555 use sdk for street validation
myparcelbe/woocommerce pull request #178
Opened 2021-11-24 10:18 UTC by markernst97

2021-11-24 14:49 UTC, EdieLemoine requested changes

2021-11-24 14:49 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
> +        $shipping_name = method_exists($order, "get_formatted_shipping_full_name")
Als je hier toch bent mag je `shipping_name` hernoemen naar `shippingName` (CTRL+T)

2021-11-24 14:49 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
> +        $shipping_country  = $order->get_shipping_country();
Deze ook

2021-11-24 14:49 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
>          $hasPickupLocation = WCX_Order::get_meta($order, WCMYPABE_Admin::META_DELIVERY_OPTIONS);
Dit moet `$deliveryOptions` heten, verwarrende naam zo

2021-11-24 14:49 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
> +                : "",
Single quotes

2021-11-24 14:49 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
> +                (string) WCX_Order::get_meta($order, "_shipping_street_name"),
Single quotes

2021-11-25 08:29 UTC, RichardPerdaan approved these changes

2021-11-25 08:58 UTC, joerivanveen approved these changes

2021-11-25 09:07 UTC, EdieLemoine requested changes

2021-11-25 09:07 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
> +        $deliveryOptions = WCX_Order::get_meta($order, WCMYPABE_Admin::META_DELIVERY_OPTIONS);
Dit blok is niet meer uitgelijnd, ff selecteren en option+shift+L

2021-11-25 10:57 UTC, EdieLemoine approved these changes

2021-12-03 13:52 UTC, EdieLemoine approved these changes

2022-01-04 13:55 UTC, closed without merging