My 30537 remove email setting
myparcelbe/woocommerce pull request #180
Opened 2021-12-03 12:42 UTC by markernst97

2021-12-03 13:51 UTC, EdieLemoine requested changes

2021-12-03 13:51 UTC, EdieLemoine commented on includes/admin/class-wcmpbe-export.php
> +        if ($shipping_country === "BE" || $shipping_country === "NL" ){
formatting klopt niet

2021-12-06 11:22 UTC, joerivanveen requested changes
In dit hele stuk raak je best veel aan qua formatting, maak dan svp ook gelijk enkele aanhalingstekens in de regels die je aanraakt.

2021-12-06 11:22 UTC, joerivanveen commented on includes/admin/class-wcmpbe-export.php
> +        $isUsingSeparateFields = WCX_Order::get_meta($order, "_billing_street_name")
Verwarrend verschillende formatting, toch?

2021-12-07 09:47 UTC, joerivanveen approved these changes
Het is overzichtelijker als je die hele formatting van die ene functie achterwege laat, zodat dat niet als wijziging gepresenteerd wordt, maar zoals besproken geen dealbreaker voor mij

2021-12-07 09:59 UTC, EdieLemoine approved these changes

2021-12-08 08:08 UTC, merged