refactor: replace getRecipientFromOrder() function with adapter for recipient class
myparcelbe/woocommerce pull request #181
Opened 2021-12-09 08:52 UTC by markernst97

2021-12-13 09:24 UTC, RichardPerdaan approved these changes

2021-12-30 10:54 UTC, joerivanveen requested changes

2021-12-30 10:54 UTC, joerivanveen commented on includes/adapter/RecipientFromWCOrder.php
> +        $streetParts  = $order->{"get_{$type}_address_1"}();
Dit is nu verwarrend voor mij, zou het hier niet `$addressLine1` moeten zijn, aangezien het een string is, en pas na `$this->separateStreet` werkelijk 'parts' zijn?

2021-12-30 11:03 UTC, joerivanveen approved these changes

2021-12-31 11:44 UTC, RichardPerdaan approved these changes

2022-01-03 10:37 UTC, merged